version: "3.8"
services:
  node_app:
    container_name: "my_first_node-app"
    build: ./back
    ports:
      - "3001:3001"
  db:
    container_name: "mongo_db"
    image: mongo:4
    ports:
      - "27017:27017"